name: Build And Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.ORACLE_HOST }}
        USERNAME: ${{ secrets.ORACLE_USERNAME }}
        PORT: ${{ secrets.ORACLE_VM_PORT }}
        KEY: ${{ secrets.ORACLE_VM_SSH_KEY }}
      with:
        source: "."
        target: "/home/opc/api"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.ORACLE_HOST }}
        USERNAME: ${{ secrets.ORACLE_USERNAME }}
        PORT: ${{ secrets.ORACLE_VM_PORT }}
        KEY: ${{ secrets.ORACLE_VM_SSH_KEY }}
        script_stop: true
        script: |
          cd /home/opc/api
          npm ci
          pm2 reload api --update-env
